# Custom Language File for Launcher Customizer

[ejs.app]
title = "Elysia Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/JeremGamingYT/Elysia-Launcher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/zNWUXdt"

[ejs.settings]
sourceGithubLink = "https://github.com/JeremGamingYT/Elysia-Launcher"
supportLink = "https://github.com/JeremGamingYT/Elysia-Launcher/issues"

[ejs.welcome]
welcomeHeader = "BIENVENUE SUR ÉLYSIA"
welcomeDescription = "ÉLYSIA est un serveur Minecraft PvP Faction."
welcomeDescCTA = "Vous êtes à quelques clics de Westeros."